collections:
  lists:
    output: true

defaults:
  - scope:
      path: ""
      type: "lists"
    values:
      layout: "piece"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "piece"
  - scope:
      path: ""
    values:
      layout: "default"

sass:
  style: compressed